export const data = [
    {
        id: 1,
        img: "./assets/img1.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 2,
        img: "./assets/img2.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 3,
        img: "./assets/img3.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 4,
        img: "./assets/img4.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 5,
        img: "./assets/img5.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 6,
        img: "./assets/img6.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 7,
        img: "./assets/img7.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 8,
        img: "./assets/img8.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
]