export const data2 = [
    {
        id: 1,
        img: "./assets/stay/1.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 2,
        img: "./assets/stay/2.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 3,
        img: "./assets/stay/3.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 4,
        img: "./assets/stay/4.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 5,
        img: "./assets/stay/5.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 6,
        img: "./assets/stay/6.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 7,
        img: "./assets/stay/7.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 8,
        img: "./assets/stay/8.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 9,
        img: "./assets/stay/9.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 10,
        img: "./assets/stay/10.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 11,
        img: "./assets/stay/11.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 12,
        img: "./assets/stay/12.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 13,
        img: "./assets/stay/13.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 14,
        img: "./assets/stay/14.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 15,
        img: "./assets/stay/15.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
    {
        id: 16,
        img: "./assets/stay/16.png",
        title: "Desert king",
        price: "1MBT per night",
        distance: "2345km away",
        duration: "available for 2 weeks stay",
    },
]